# Generated by Django 4.2.4 on 2023-08-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
