# Generated by Django 4.2.4 on 2023-08-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_remove_chapter_chapternum_chapter_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapterNumber',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
