# Generated by Django 4.2.4 on 2023-08-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_chapter_chapternumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookclubComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
