# Generated by Django 4.2.4 on 2023-09-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0009_bookuserrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuserrelation',
            name='lastChapterComplete',
            field=models.IntegerField(default=-1),
        ),
    ]
