# Generated by Django 4.2.4 on 2023-09-17 19:57

from django.db import migrations


def set_default_bookmarked_chapter(apps, schema_editor):
    BookUserRelation = apps.get_model("bookclub", "BookUserRelation")
    BookUserRelation.objects.filter(bookmarkedChapter=None).update(bookmarkedChapter=-1)
    BookUserRelation.objects.filter(bookmarkedPage=None).update(bookmarkedPage=-1)


class Migration(migrations.Migration):
    dependencies = [
        ("bookclub", "0011_bookuserrelation_bookmarkedchapter_and_more"),
    ]

    operations = [migrations.RunPython(set_default_bookmarked_chapter)]
