# Generated by Django 4.2.4 on 2023-10-10 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0011_bookuserrelation_bookmarkedchapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuserrelation',
            name='bookmarkedPage',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
