# Generated by Django 4.2.4 on 2023-10-26 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0012_alter_bookuserrelation_bookmarkedpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuserrelation',
            name='bookmarkedPage',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
