# Generated by Django 4.2.4 on 2023-08-23 03:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chores', '0004_chore_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='user',
        ),
        migrations.AddField(
            model_name='chore',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
